### ISSUE TITLE
NET 6 Support

### ISSUE THREAD

**Issue by aritchie** [redth-org/AndHUD#52]
## 🚀 Feature Requests
Compile for net6.0-android.  Branch available here: https://github.com/aritchie/AndHUD

Happy to send PR

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Happy to take a PR.

Does it build nicely using MSBuild.SDK.Extras? I recently had a bad time and had to switch the project over to Xamarin.Legacy.SDK to support both the older xamarin targets and the new net6.0.

**Comment by aritchie** [comment]
It isn't building nicely with Xamarin.Legacy.SDK or sdk extras on the latest VS.  Might have to wait for something tooling fixes... :(
