### ISSUE TITLE
Could not install package 'AndHUD 2.0.1'

### ISSUE THREAD

**Issue by ClarenceMG** [redth-org/AndHUD#57]
## 🐛 Bug Report

Could not install package 'AndHUD 2.0.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v13.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Expected behavior

Update the package

### Reproduction steps

Try to update the package in Xamarin.Android project

### Configuration

**Version:**  2.0.1

**Platform:** 
- [X] :robot: Xamarin.Android

**Comment by Cheesebaron** [comment]
MonoAndroid is not supported since version 2.0.0 use an older version or make a fork
