### ISSUE TITLE
Loader without frame

### ISSUE THREAD

**Issue by acaliaro** [redth-org/AndHUD#59]
## 💬 Questions and Help

Is it possible to have a loader without frame an text (only the loader...) @Cheesebaron @Redth thanks!

**Comment by Cheesebaron** [comment]
Do you want to change it for all occurrences or just one?

If you want to override the behavior you can always just create these layouts in your Application project and change the visuals:

https://github.com/redth-org/AndHUD/tree/main/AndHUD/Resources/layout

So adding:

- Resources/layout/loading.xml
- Resources/layout/loadingimage.xml
- Resources/layout/loadingprogress.xml

Make sure Id's are the same as in here, or it might crash with null refs.

If you want to change for one occurrence, that will be a bit more challenging. We currently do not have a way to override the default behavior and do not expose the inflated layout. Perhaps you could get it from `AndHUD.Shared.CurrentDialog` somehow.
